import type { NextConfig } from "next";
import withSerwistInit from "@serwist/next";

const isDev = process.env.NODE_ENV === "development";

const nextConfig: NextConfig = {
  images: {
    unoptimized: true,
  },
};

// @serwist/next v9 only hooks Next's `webpack` config and does NOT support
// Turbopack (it warns as much). Next 16 uses Turbopack by default for `next
// dev`, so the mere presence of Serwist's webpack config breaks the dev server.
// Serwist is disabled in dev anyway, so skip the wrapper entirely there and run
// pure Turbopack. The production service worker is still generated by
// `next build --webpack` (see package.json).
//
// Note: we intentionally do NOT set `turbopack.root`. Any value there breaks
// Tailwind v4's `@import "tailwindcss"` resolution under Turbopack here; the
// remaining "inferred workspace root" lockfile warning is cosmetic and safe.
const withSerwist = withSerwistInit({
  swSrc: "app/sw.ts",
  swDest: "public/sw.js",
  disable: isDev,
});

export default isDev ? nextConfig : withSerwist(nextConfig);
